"""empty message

Revision ID: 75fc1e4f6cfe
Revises: 
Create Date: 2023-05-01 20:21:23.781145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fc1e4f6cfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connectiontest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2', sa.String(), nullable=True))
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connectiontest', schema=None) as batch_op:
        batch_op.drop_column('test2')

    # ### end Alembic commands ###
